# Generated by Django 2.0.3 on 2018-08-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='assetValueAtPurchase',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='assetValueNow',
            field=models.FloatField(default=0),
        ),
    ]
